### PR TITLE
make scanner return the number of vulnarable packages

### PR DESCRIPTION
**Pull request by chiluap**
Firstly. Thanks for all the work.
Realised that the Scan function is allways returning 0 if there is no Exception.
;=)

### CODE REVIEW

**Comment by chiluap** [comment]
Added a commit, did not see that vulnDict was 2-Dimentional ;=)

**Comment by chiluap** [comment]
Sorry for alle the bother:
it is working now in the prerelease version of NuGetDefense.Lib --version 3.2.0-prerelease6

Two things however happen to me:

1. If I do not delete the sqlight database, a secound run fails to report the original vulnarable packages.
2. the json report shows the count but fails to serialize the packages array

```json
{
  "VulnerabilitiesCount": 11,
  "Packages": []
}
```

Shall I create issues for this?

You may close this PR.
Thank you =)

**Comment by digitalcoyote** [comment]
Go ahead, I'm reworking the queries used for that cache, but having it reported will let others know it's a known issue now.

**Comment by chiluap** [comment]
closing the PR.

thank you for your time and work.

c.

**Pull request closed without merging**
